BkpClasif/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

app_name = 'clasificacion'
urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name="clasificacion.html"), name='clasificacion'),
]

Educadatos/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', TemplateView.as_view(template_name="index.html")),
    url(r'^mychart$', TemplateView.as_view(template_name="mychart.html")),
    url(r'^google7ecc988dde80334f.html$', TemplateView.as_view(template_name="google-search.html")),
    url(r'^saber2017/', include('saber2017.urls')),
    url(r'^saber2016/', include('saber2016.urls')),
    url(r'^clasificacion/', include('clasification.urls')),
]

saber2016/urls.py
from django.conf.urls import url
from . import views

app_name = 'saber2016'
urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^(?P<slug>[\w+-]+)/(?P<pk>\d+)/detalle/$', views.detalle, name="detalle"),
    url(r'^listado/$', views.proc_colegio, name="proc_colegio"),
]

saber2017/urls.py
from django.conf.urls import url
from . import views

app_name = 'saber2017'
urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^(?P<slug>[\w+-]+)/(?P<pk>\d+)/detalle/$', views.detalle, name="detalle"),
    url(r'^listado/$', views.proc_colegio, name="proc_colegio"),
]

saber2017/models.py
from django.db import models
from django.utils.text import slugify

class Colegio(models.Model):
    nombreinstitucion = models.CharField(max_length=100, blank=True, null=True)
    codinst = models.CharField(max_length=20, blank=True, null=True)
    nombremunicipio = models.CharField(max_length=100, blank=True, null=True)
    codigomunicipio = models.IntegerField(blank=True, null=True)
    departamento = models.CharField(max_length=100, blank=True, null=True)
    calendario = models.CharField(max_length=2, blank=True, null=True)
    naturaleza = models.CharField(max_length=30, blank=True, null=True)
    evaluados = models.IntegerField(blank=True, null=True)
    prommatematica = models.FloatField(blank=True, null=True)
    promsocialesyciudadanas = models.FloatField(blank=True, null=True)
    promingles = models.FloatField(blank=True, null=True)
    promcienciasnaturales = models.FloatField(blank=True, null=True)
    promlecturacritica = models.FloatField(blank=True, null=True)
    jornada = models.CharField(max_length=50, blank=True, null=True)
    periodo = models.IntegerField(blank=True, null=True)
    puntajeglobal = models.FloatField(blank=True, null=True)
    slug = models.SlugField(max_length=200, null=True, blank=True)

    def __str__(self):
        return self.nombreinstitucion

    def save(self, *args, **kwargs):
        self.puntajeglobal = ((self.prommatematica + self.promsocialesyciudadanas + self.promcienciasnaturales + self.promlecturacritica) * 3 + self.promingles) / 13.0 * 5
        self.puntajeglobal = round(self.puntajeglobal, 2)
        self.slug = slugify(self.nombreinstitucion)
        super(Colegio, self).save(*args, **kwargs)

    class Meta:
        db_table = 'colegio'


class Departamento(models.Model):
    nombre = models.CharField(max_length=150)

    def __str__(self):
        return self.nombre

class Municipio(models.Model):
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=200)

    def __str__(self):
        return self.nombre

    class Meta:
        ordering = ['nombre']

ASIGNATURAS = (
    ('matematicas', 'Matematicas'),
    ('ciencias', 'Ciencias'),
    ('sociales', 'Sociales y Ciudadanas'),
	('competencias', 'Competencias Ciudadanas'),
	('ingles', 'Ingles'),
	('razonamiento', 'Razonamiento Cuantitativo'),
	('lectura', 'Lectura Critica'),
)

class Asignatura(models.Model):
    nombre = models.CharField(max_length=100, choices=ASIGNATURAS)

    def __str__(self):
        return self.get_nombre_display()

saber2017/forms.py
from django import forms

class BootstrapForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(BootstrapForm, self).__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control mr-sm-2'
            })

class ColegioForm(BootstrapForm):
    colegio = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'required': True, 'placeholder': 'Buscar'}))
    #ciudad = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'required': True, 'placeholder': 'medellin'}))

    def clean(self):
        return dict((k, v.upper()) for k, v in self.cleaned_data.items())

class ColegioComparaForm(forms.Form):
    colegio1 = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'required': True, 'placeholder': 'ejemplo: montessori'}))
    ciudad1 = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'required': True, 'placeholder': 'medellin'}))
    colegio2 = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'required': True, 'placeholder': 'la salle'}))
    ciudad2 = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'required': True, 'placeholder': 'barranquilla'}))

saber2017/views.py
from django.shortcuts import render
from saber2017.models import Colegio
from saber2016.models import Colegio16
from django.core import serializers
from .forms import ColegioForm

def home(request):
    datos = Colegio.objects.filter(
                puntajeglobal__gt=72).order_by(
                '-puntajeglobal').exclude(evaluados__lt=5)[:100]
    encabezado = "Pruebas Saber 11 2017: Listado de los Mejores Colegios"
    contexto = {'datos': datos, 'encabezado': encabezado}
    return render(request, 'home.html', contexto)

def detalle(request, slug, pk):
    valor = Colegio.objects.get(pk=pk)
    colegio = valor
    valor = serializers.serialize("json", [valor])
    return render(request, 'detalle.html', {'datos': valor, 'colegio': colegio})

def proc_colegio(request):
    #print("Comenzando")
    if request.method == 'POST':
        #print("Segundo paso")
        form = ColegioForm(request.POST)
        #print(form.as_p())
        #print(form.is_valid())
        #print(form.cleaned_data)
        if form.is_valid() and len(form.cleaned_data['colegio'].strip()) > 3:
            nombre_colegio = form.cleaned_data['colegio'].strip()
            #print("Tercer paso")
            #print(nombre_colegio)
            try:
                lista_colegios = Colegio.objects.filter(nombreinstitucion__iregex=nombre_colegio)
            except Colegio.DoesNotExist:
                lista_colegios = []
            try:
                lista_colegios16 = Colegio16.objects.filter(nombreinstitucion__iregex=nombre_colegio)
            except Colegio16.DoesNotExist:
                lista_colegios16 = []
            #print(lista_colegios)
            if len(lista_colegios) == 0 and len(lista_colegios16) == 0:
                form = ColegioForm()
                mensaje = "Intente de nuevo. No se encontraron datos"
                return render(request, 'search_results.html', {'form': form, 'mensaje': mensaje})
            elif len(lista_colegios) >= 1 or len(lista_colegios16) >= 1:
                lista_colegios = lista_colegios.union(lista_colegios16)
                return render(request, 'search_results.html', {'datos': lista_colegios, 'titulo': 'Resultados de la Búsqueda' })
        else:
            form = ColegioForm()
            return render(request, 'search_results.html', {'form': form, 'data': 0})
    else:
        form = ColegioForm()
        return render(request, 'search_results.html', {'form': form, 'data': 0})

saber2017/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
    <style>
      .bg-inverse {
         background-color: #364a94!important;
      }
      .container {
        margin-top: 6em;
      }
    </style>
    <meta charset="utf-8">
    {% if title %}
        <meta name="description" content="Resultados de las Pruebas Saber 11 para el colegio {{title}}">
    {% else %}
        <meta name="description" content="Muestra los resultados de las Pruebas Saber 11 organizadas por el ICFES en los años 2016 y 2017">
    {% endif %}
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    
	<!-- Static navbar -->
    <nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="/">Educadatos</a>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Resultados Saber</a>
            <div class="dropdown-menu" aria-labelledby="dropdown01">
              <a class="dropdown-item" href="#">Pruebas Saber 2016</a>
              <a class="dropdown-item" href="#">Another action</a>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="/saber2017/">Pruebas Saber 2017 <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/saber2016/">Pruebas Saber 2016</a>
          </li>
          <!--
          <li class="nav-item">
            <a class="nav-link disabled" href="#">MOOCs</a>
          </li>
          -->
        </ul>
        <form class="form-inline my-2 my-lg-0" action="{% url 'saber2017:proc_colegio' %}" method="post">
          {% csrf_token %}
          {{ form.colegio }}
          <!-- <input class="form-control mr-sm-2" type="text" placeholder="Buscar"> -->
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Buscar</button>
        </form>
      </div>
    </nav>    

    <div class="container">
	{% block content%}
	{% endblock %}
    </div><!-- container -->
    
    <footer class="footer">
        <div class="container text-center">
            <small> Educadatos {% now "F Y" %}</small>
        </div>
    </footer>
     <!-- Bootstrap core JavaScript and Others like Chart.js
    ================================================== -->
    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
</body>
</html>

saber2017/templates/detalle.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}{{colegio.nombreinstitucion}}{% endblock %}
{% block content %}
 <h1 class="text-center">{{colegio.nombreinstitucion}} {% if colegio.enlace %}<span style="font-size: 0.5em"><a href="{{colegio.enlace}}">(Enlace para resultados 2016)</a></span>{% endif %}</h1>

<canvas id="myChart" width="400" height="200"></canvas>

<div class="card">
  <div class="card-block">
    <h4 class="card-title card-header">{{colegio.nombreinstitucion}}</h4>
    <div class="row">
      <div class="col-sm-6">
        <p class="card-text">Municipio: {{colegio.nombremunicipio}}</p>
        <p class="card-text">Naturaleza: {{colegio.naturaleza}}</p>
        <p class="card-text">Calendario: {{colegio.calendario}}</p>
        <p class="card-text">Evaluados: {{colegio.evaluados}}</p>
      </div>
      <div class="col-sm-6">
        <p class="card-text">Puntaje Global: {{colegio.puntajeglobal | floatformat:"0"}}</p>
        <p class="card-text">Periodo: {{colegio.periodo}}</p>
        <p class="card-text">Jornada: {{colegio.jornada}}</p>
        <p class="card-text">Código Institución: {{colegio.codinst}}</p>
      </div>
    </div>
  </div>
</div>

<script>
	var dattos = {{ datos | safe }};
	var datta = dattos[0].fields;
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.6.0/Chart.min.js"></script>
<script async src="{% static 'js/visor.js' %}"></script>
{% endblock %}

saber2017/templates/home.html
{% extends 'base.html' %}
{% block title %}{{encabezado}}{% endblock %}
{% block content %}
<h2>{{encabezado}}</h2>
<ol class="list-group">
    {% for elem in datos %}
      <li class="list-group-item"><a href="{% url 'saber2017:detalle' elem.slug elem.pk %}">{{ forloop.counter }}. {{elem}} ({{elem.nombremunicipio}}). Puntaje Global: {{elem.puntajeglobal | floatformat:"0"}}</a></li>
    {% endfor %}
</ol>
{% endblock %}

saber2017/templates/index.html
{% extends 'miapp/base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% block title %}
{% if colegio%}
  {{colegio.nombre}}
{% else %}
  buscar colegio pruebas saber 11 2015 icfes
{% endif %}
{% endblock %}
{% block content %}
{% if colegio %}
        <h1 class="text-center">{{colegio.nombre}} {% if colegio.enlace %}<span style="font-size: 0.5em"><a href="{{colegio.enlace}}">(Enlace para resultados 2016)</a></span>{% endif %}</h1>
        <div class="table-responsive">
	<table class="table">
		<tr>
			<th>Ciudad</th>
			<th>Evaluados</th>
			<th>Naturaleza</th>
			<th>Calendario</th>
                        <th>Ranking</th>
		</tr>
		<tr>
			<td>{{colegio.municipio}}</td>
			<td>{{colegio.evaluados}}</td>
			<td>{{colegio.naturaleza}}</td>
			<td>{{colegio.calendario}}</td>
                        <td>{{colegio.puesto}}</td>
		</tr>
	</table>
        </div> <!-- end table responsive -->
{% endif %}
<div id="grafica"></div>
{% if mensaje %}<h3>{{mensaje}}</h3>{% endif %}
{% if not colegio %}
<div class="row">
  <div class="col-md-6 azul-claro">
  <h1 class="text-center color-blanco">Buscar Resultados Individuales</h1>
    <form action="" method='POST'>
	{% csrf_token %}
	{{form | crispy}}
	<button type="submit" class="btn btn-primary">Buscar</button>
    </form>
  </div>
</div>
{% endif %}
<script>
	var dotado = {{data | safe}};
	if (dotado != 0) {
		var data = dotado[0].fields;
	}
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.6/d3.min.js" charset="utf-8"></script>
<script async src="{% static 'js/visor.js' %}"></script>
{% endblock %}

saber2017/templates/search_results.html
{% extends 'base.html' %}
{% block title %}{{encabezado}}{% endblock %}
{% block content %}
{% if mensaje %}
  {{ mensaje }}
{% endif %}
<h2>{{ titulo }}</h2>
<ol class="list-group">
    {% for elem in datos %}
      {% if elem.periodo == 2017 %}
          <li class="list-group-item"><a href="{% url 'saber2017:detalle' elem.slug elem.pk %}">{{elem}}, {{elem.nombremunicipio}} {{elem.periodo}}</a></li>
      {% else %}
          <li class="list-group-item"><a href="{% url 'saber2016:detalle' elem.slug elem.pk %}">{{elem}}, {{elem.nombremunicipio}} {{elem.periodo}}</a></li>
      {% endif %}
    {% endfor %}
</ol>
{% endblock %}