BkpClasif/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

app_name = 'clasificacion'
urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name="clasificacion.html"), name='clasificacion'),
]

Educadatos/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', TemplateView.as_view(template_name="index.html")),
    url(r'^mychart$', TemplateView.as_view(template_name="mychart.html")),
    url(r'^google7ecc988dde80334f.html$', TemplateView.as_view(template_name="google-search.html")),
    url(r'^saber2017/', include('saber2017.urls')),
    url(r'^saber2016/', include('saber2016.urls')),
    url(r'^clasificacion/', include('clasification.urls')),
]

clasification/urls.py
from django.conf.urls import url
from . import views

app_name = 'clasification'
urlpatterns = [
    url(r'^$', views.index, name='clasificacion'),
    url(r'^(?P<dato_pk>[0-9]+)/$', views.detalle, name='detalle'),
]

clasification/models.py
from django.db import models

class School(models.Model):
    nombre = models.CharField(max_length=200, blank=True, null=True)
    municipio = models.CharField(max_length=100, blank=True, null=True)
    codigo_dane = models.CharField(max_length=30, blank=True, null=True)
    sector = models.CharField(max_length=50, blank=True, null=True)
    tipo = models.CharField(max_length=50, blank=True, null=True)
    clasificacion = models.CharField(max_length=10, blank=True, null=True)
    evaluados = models.IntegerField(blank=True, null=True)
    matriculados = models.IntegerField(blank=True, null=True)
    ingles = models.FloatField(blank=True, null=True)
    sociales = models.FloatField(blank=True, null=True)
    matematicas = models.FloatField(blank=True, null=True)
    ciencias = models.FloatField(blank=True, null=True)
    lectura = models.FloatField(blank=True, null=True)
    total = models.FloatField(blank=True, null=True)

    def __str__(self):
        return self.nombre

clasification/views.py
from django.shortcuts import render, get_object_or_404

from clasification.models import School

def index(request):
    datos = School.objects.all()[:100]
    return render(request, 'clasification/clasificacion.html', {'datos': datos})

def detalle(request, dato_pk):
    skool = get_object_or_404(School, pk=dato_pk)
    return render(request, 'clasification/detalle.html', {'skool': skool})

clasification/templates/clasification/clasificacion.html
{% extends 'base.html' %}

{% block title %}Clasificación de los planteles del Año 2016{% endblock %}

{% block content %}
    <div class="container">
        <h1 class="display-4 text-center">Pruebas Saber 11: Clasificación del Año 2016</h1>
        <p class="lead">
         Esta es la lista de los primeros 100 colegios
        </p>
        <ol>
            {% for dato in datos %}
                <li><a href="{% url 'clasification:detalle' dato.pk %}">{{dato.nombre}}</a></li>
            {% endfor %}
        </ol>
    </div>
{% endblock %}

clasification/templates/clasification/detalle.html
{% extends 'base.html' %}

{% block title %}{{skool.nombre}}{% endblock %}

{% block content %}
    <div class="container">
        <p>{{skool}}</p>
        <p>{{skool.total}}</p>
        <p>{{skool.clasificacion}}</p>
    </div>
{% endblock %}